#!/bin/bash

# list of design files to be compiled

ver_files=("../../source/qam_top.v"
		"../../source/coeff_memory.v"
		"../../source/dsp_slice.v"
		"../../source/fir_filter.v"
		"../../source/reset_synchronization.v"
		"../../source/SPI_Interface.v"
		"../../source/upsampler.v"
		"../../source/dsp_top.v"
	   	"../testbench/qam_top.v"
		"../testbench/dsp_top_tb.v"
		)	
