#!/bin/bash

# list of design files to be compiled

ver_files=("../../source/dsp_slice.v"
           "../../source/coeff_memory.v"
           "../../source/fir_filter.v"
	   "../../source/upsampler.v"
           "../../source/TopModule.v"
	   "../testbench/TopModule_tb.v"
	   "../testbench/fir_filter_tb.v"
           )
	
