###################################################################

# Created by write_sdc on Thu Apr 24 19:43:30 2025

###################################################################
set sdc_version 2.1

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_max_capacitance 0.5 [current_design]
set_max_transition 1.5 [current_design]
set_load -pin_load 0.2 [get_ports {sample_out[3]}]
set_load -pin_load 0.2 [get_ports {sample_out[2]}]
set_load -pin_load 0.2 [get_ports {sample_out[1]}]
set_load -pin_load 0.2 [get_ports {sample_out[0]}]
set_load -pin_load 0.2 [get_ports {accum_out[11]}]
set_load -pin_load 0.2 [get_ports {accum_out[10]}]
set_load -pin_load 0.2 [get_ports {accum_out[9]}]
set_load -pin_load 0.2 [get_ports {accum_out[8]}]
set_load -pin_load 0.2 [get_ports {accum_out[7]}]
set_load -pin_load 0.2 [get_ports {accum_out[6]}]
set_load -pin_load 0.2 [get_ports {accum_out[5]}]
set_load -pin_load 0.2 [get_ports {accum_out[4]}]
set_load -pin_load 0.2 [get_ports {accum_out[3]}]
set_load -pin_load 0.2 [get_ports {accum_out[2]}]
set_load -pin_load 0.2 [get_ports {accum_out[1]}]
set_load -pin_load 0.2 [get_ports {accum_out[0]}]
set_max_fanout 1 [get_ports clk]
set_max_fanout 1 [get_ports {sample_in[3]}]
set_max_fanout 1 [get_ports {sample_in[2]}]
set_max_fanout 1 [get_ports {sample_in[1]}]
set_max_fanout 1 [get_ports {sample_in[0]}]
set_max_fanout 1 [get_ports {accum_in[11]}]
set_max_fanout 1 [get_ports {accum_in[10]}]
set_max_fanout 1 [get_ports {accum_in[9]}]
set_max_fanout 1 [get_ports {accum_in[8]}]
set_max_fanout 1 [get_ports {accum_in[7]}]
set_max_fanout 1 [get_ports {accum_in[6]}]
set_max_fanout 1 [get_ports {accum_in[5]}]
set_max_fanout 1 [get_ports {accum_in[4]}]
set_max_fanout 1 [get_ports {accum_in[3]}]
set_max_fanout 1 [get_ports {accum_in[2]}]
set_max_fanout 1 [get_ports {accum_in[1]}]
set_max_fanout 1 [get_ports {accum_in[0]}]
set_max_fanout 1 [get_ports {coeff_in[7]}]
set_max_fanout 1 [get_ports {coeff_in[6]}]
set_max_fanout 1 [get_ports {coeff_in[5]}]
set_max_fanout 1 [get_ports {coeff_in[4]}]
set_max_fanout 1 [get_ports {coeff_in[3]}]
set_max_fanout 1 [get_ports {coeff_in[2]}]
set_max_fanout 1 [get_ports {coeff_in[1]}]
set_max_fanout 1 [get_ports {coeff_in[0]}]
create_clock [get_ports clk]  -period 10  -waveform {0 5}
set_clock_latency 0.5  [get_clocks clk]
set_clock_uncertainty -setup 0.5  [get_clocks clk]
set_clock_uncertainty -hold 0.3  [get_clocks clk]
set_clock_transition -max -rise 0.1 [get_clocks clk]
set_clock_transition -min -rise 0.1 [get_clocks clk]
set_clock_transition -max -fall 0.12 [get_clocks clk]
set_clock_transition -min -fall 0.12 [get_clocks clk]
create_clock -name v_clk  -period 10  -waveform {0 5}
set_input_delay -clock v_clk  3  [get_ports {sample_in[3]}]
set_input_delay -clock v_clk  3  [get_ports {sample_in[2]}]
set_input_delay -clock v_clk  3  [get_ports {sample_in[1]}]
set_input_delay -clock v_clk  3  [get_ports {sample_in[0]}]
set_input_delay -clock v_clk  3  [get_ports {accum_in[11]}]
set_input_delay -clock v_clk  3  [get_ports {accum_in[10]}]
set_input_delay -clock v_clk  3  [get_ports {accum_in[9]}]
set_input_delay -clock v_clk  3  [get_ports {accum_in[8]}]
set_input_delay -clock v_clk  3  [get_ports {accum_in[7]}]
set_input_delay -clock v_clk  3  [get_ports {accum_in[6]}]
set_input_delay -clock v_clk  3  [get_ports {accum_in[5]}]
set_input_delay -clock v_clk  3  [get_ports {accum_in[4]}]
set_input_delay -clock v_clk  3  [get_ports {accum_in[3]}]
set_input_delay -clock v_clk  3  [get_ports {accum_in[2]}]
set_input_delay -clock v_clk  3  [get_ports {accum_in[1]}]
set_input_delay -clock v_clk  3  [get_ports {accum_in[0]}]
set_input_delay -clock v_clk  3  [get_ports {coeff_in[7]}]
set_input_delay -clock v_clk  3  [get_ports {coeff_in[6]}]
set_input_delay -clock v_clk  3  [get_ports {coeff_in[5]}]
set_input_delay -clock v_clk  3  [get_ports {coeff_in[4]}]
set_input_delay -clock v_clk  3  [get_ports {coeff_in[3]}]
set_input_delay -clock v_clk  3  [get_ports {coeff_in[2]}]
set_input_delay -clock v_clk  3  [get_ports {coeff_in[1]}]
set_input_delay -clock v_clk  3  [get_ports {coeff_in[0]}]
set_output_delay -clock v_clk  3  [get_ports {sample_out[3]}]
set_output_delay -clock v_clk  3  [get_ports {sample_out[2]}]
set_output_delay -clock v_clk  3  [get_ports {sample_out[1]}]
set_output_delay -clock v_clk  3  [get_ports {sample_out[0]}]
set_output_delay -clock v_clk  3  [get_ports {accum_out[11]}]
set_output_delay -clock v_clk  3  [get_ports {accum_out[10]}]
set_output_delay -clock v_clk  3  [get_ports {accum_out[9]}]
set_output_delay -clock v_clk  3  [get_ports {accum_out[8]}]
set_output_delay -clock v_clk  3  [get_ports {accum_out[7]}]
set_output_delay -clock v_clk  3  [get_ports {accum_out[6]}]
set_output_delay -clock v_clk  3  [get_ports {accum_out[5]}]
set_output_delay -clock v_clk  3  [get_ports {accum_out[4]}]
set_output_delay -clock v_clk  3  [get_ports {accum_out[3]}]
set_output_delay -clock v_clk  3  [get_ports {accum_out[2]}]
set_output_delay -clock v_clk  3  [get_ports {accum_out[1]}]
set_output_delay -clock v_clk  3  [get_ports {accum_out[0]}]
set_input_transition -max -rise 0.1  [get_ports clk]
set_input_transition -max -fall 0.12  [get_ports clk]
set_input_transition -min -rise 0.1  [get_ports clk]
set_input_transition -min -fall 0.12  [get_ports clk]
set_input_transition -max -rise 0.1  [get_ports {sample_in[3]}]
set_input_transition -max -fall 0.12  [get_ports {sample_in[3]}]
set_input_transition -min -rise 0.1  [get_ports {sample_in[3]}]
set_input_transition -min -fall 0.12  [get_ports {sample_in[3]}]
set_input_transition -max -rise 0.1  [get_ports {sample_in[2]}]
set_input_transition -max -fall 0.12  [get_ports {sample_in[2]}]
set_input_transition -min -rise 0.1  [get_ports {sample_in[2]}]
set_input_transition -min -fall 0.12  [get_ports {sample_in[2]}]
set_input_transition -max -rise 0.1  [get_ports {sample_in[1]}]
set_input_transition -max -fall 0.12  [get_ports {sample_in[1]}]
set_input_transition -min -rise 0.1  [get_ports {sample_in[1]}]
set_input_transition -min -fall 0.12  [get_ports {sample_in[1]}]
set_input_transition -max -rise 0.1  [get_ports {sample_in[0]}]
set_input_transition -max -fall 0.12  [get_ports {sample_in[0]}]
set_input_transition -min -rise 0.1  [get_ports {sample_in[0]}]
set_input_transition -min -fall 0.12  [get_ports {sample_in[0]}]
set_input_transition -max -rise 0.1  [get_ports {accum_in[11]}]
set_input_transition -max -fall 0.12  [get_ports {accum_in[11]}]
set_input_transition -min -rise 0.1  [get_ports {accum_in[11]}]
set_input_transition -min -fall 0.12  [get_ports {accum_in[11]}]
set_input_transition -max -rise 0.1  [get_ports {accum_in[10]}]
set_input_transition -max -fall 0.12  [get_ports {accum_in[10]}]
set_input_transition -min -rise 0.1  [get_ports {accum_in[10]}]
set_input_transition -min -fall 0.12  [get_ports {accum_in[10]}]
set_input_transition -max -rise 0.1  [get_ports {accum_in[9]}]
set_input_transition -max -fall 0.12  [get_ports {accum_in[9]}]
set_input_transition -min -rise 0.1  [get_ports {accum_in[9]}]
set_input_transition -min -fall 0.12  [get_ports {accum_in[9]}]
set_input_transition -max -rise 0.1  [get_ports {accum_in[8]}]
set_input_transition -max -fall 0.12  [get_ports {accum_in[8]}]
set_input_transition -min -rise 0.1  [get_ports {accum_in[8]}]
set_input_transition -min -fall 0.12  [get_ports {accum_in[8]}]
set_input_transition -max -rise 0.1  [get_ports {accum_in[7]}]
set_input_transition -max -fall 0.12  [get_ports {accum_in[7]}]
set_input_transition -min -rise 0.1  [get_ports {accum_in[7]}]
set_input_transition -min -fall 0.12  [get_ports {accum_in[7]}]
set_input_transition -max -rise 0.1  [get_ports {accum_in[6]}]
set_input_transition -max -fall 0.12  [get_ports {accum_in[6]}]
set_input_transition -min -rise 0.1  [get_ports {accum_in[6]}]
set_input_transition -min -fall 0.12  [get_ports {accum_in[6]}]
set_input_transition -max -rise 0.1  [get_ports {accum_in[5]}]
set_input_transition -max -fall 0.12  [get_ports {accum_in[5]}]
set_input_transition -min -rise 0.1  [get_ports {accum_in[5]}]
set_input_transition -min -fall 0.12  [get_ports {accum_in[5]}]
set_input_transition -max -rise 0.1  [get_ports {accum_in[4]}]
set_input_transition -max -fall 0.12  [get_ports {accum_in[4]}]
set_input_transition -min -rise 0.1  [get_ports {accum_in[4]}]
set_input_transition -min -fall 0.12  [get_ports {accum_in[4]}]
set_input_transition -max -rise 0.1  [get_ports {accum_in[3]}]
set_input_transition -max -fall 0.12  [get_ports {accum_in[3]}]
set_input_transition -min -rise 0.1  [get_ports {accum_in[3]}]
set_input_transition -min -fall 0.12  [get_ports {accum_in[3]}]
set_input_transition -max -rise 0.1  [get_ports {accum_in[2]}]
set_input_transition -max -fall 0.12  [get_ports {accum_in[2]}]
set_input_transition -min -rise 0.1  [get_ports {accum_in[2]}]
set_input_transition -min -fall 0.12  [get_ports {accum_in[2]}]
set_input_transition -max -rise 0.1  [get_ports {accum_in[1]}]
set_input_transition -max -fall 0.12  [get_ports {accum_in[1]}]
set_input_transition -min -rise 0.1  [get_ports {accum_in[1]}]
set_input_transition -min -fall 0.12  [get_ports {accum_in[1]}]
set_input_transition -max -rise 0.1  [get_ports {accum_in[0]}]
set_input_transition -max -fall 0.12  [get_ports {accum_in[0]}]
set_input_transition -min -rise 0.1  [get_ports {accum_in[0]}]
set_input_transition -min -fall 0.12  [get_ports {accum_in[0]}]
set_input_transition -max -rise 0.1  [get_ports {coeff_in[7]}]
set_input_transition -max -fall 0.12  [get_ports {coeff_in[7]}]
set_input_transition -min -rise 0.1  [get_ports {coeff_in[7]}]
set_input_transition -min -fall 0.12  [get_ports {coeff_in[7]}]
set_input_transition -max -rise 0.1  [get_ports {coeff_in[6]}]
set_input_transition -max -fall 0.12  [get_ports {coeff_in[6]}]
set_input_transition -min -rise 0.1  [get_ports {coeff_in[6]}]
set_input_transition -min -fall 0.12  [get_ports {coeff_in[6]}]
set_input_transition -max -rise 0.1  [get_ports {coeff_in[5]}]
set_input_transition -max -fall 0.12  [get_ports {coeff_in[5]}]
set_input_transition -min -rise 0.1  [get_ports {coeff_in[5]}]
set_input_transition -min -fall 0.12  [get_ports {coeff_in[5]}]
set_input_transition -max -rise 0.1  [get_ports {coeff_in[4]}]
set_input_transition -max -fall 0.12  [get_ports {coeff_in[4]}]
set_input_transition -min -rise 0.1  [get_ports {coeff_in[4]}]
set_input_transition -min -fall 0.12  [get_ports {coeff_in[4]}]
set_input_transition -max -rise 0.1  [get_ports {coeff_in[3]}]
set_input_transition -max -fall 0.12  [get_ports {coeff_in[3]}]
set_input_transition -min -rise 0.1  [get_ports {coeff_in[3]}]
set_input_transition -min -fall 0.12  [get_ports {coeff_in[3]}]
set_input_transition -max -rise 0.1  [get_ports {coeff_in[2]}]
set_input_transition -max -fall 0.12  [get_ports {coeff_in[2]}]
set_input_transition -min -rise 0.1  [get_ports {coeff_in[2]}]
set_input_transition -min -fall 0.12  [get_ports {coeff_in[2]}]
set_input_transition -max -rise 0.1  [get_ports {coeff_in[1]}]
set_input_transition -max -fall 0.12  [get_ports {coeff_in[1]}]
set_input_transition -min -rise 0.1  [get_ports {coeff_in[1]}]
set_input_transition -min -fall 0.12  [get_ports {coeff_in[1]}]
set_input_transition -max -rise 0.1  [get_ports {coeff_in[0]}]
set_input_transition -max -fall 0.12  [get_ports {coeff_in[0]}]
set_input_transition -min -rise 0.1  [get_ports {coeff_in[0]}]
set_input_transition -min -fall 0.12  [get_ports {coeff_in[0]}]
